### GET - Buscar posts
GET http://localhost:4321/api/post/getPosts.json
Content-Type: application/json


### GET - Buscar posts
GET http://localhost:4321/api/post/methods.json
Content-Type: application/json


### POST - Criar post
POST http://localhost:4321/api/post/methods.json
Content-Type: application/json

{
  "title": "Meu primeiro post",
  "body": "Conteúdo do post",
  "userId": 1
}
